"""
blockchain_service.py
---------------------
Handles all Web3 interaction with the FarmInsurance smart contract on Sepolia.
The backend acts as a trusted oracle — it's the only address allowed to
call triggerPayout() on the contract.
"""

import json
import os
from web3 import Web3
from web3.middleware import ExtraDataToPOAMiddleware
from src.core.config import settings

# Path to compiled contract ABI — generated by `npx hardhat compile`
_ABI_PATH = os.path.join(
    os.path.dirname(__file__), "..", "..", "..", "blockchain", "artifacts",
    "contracts", "FarmInsurance.sol", "FarmInsurance.json"
)


def _get_w3() -> Web3:
    w3 = Web3(Web3.HTTPProvider(settings.SEPOLIA_RPC_URL))
    w3.middleware_onion.inject(ExtraDataToPOAMiddleware, layer=0)
    return w3


def _get_contract(w3: Web3):
    with open(_ABI_PATH) as f:
        artifact = json.load(f)
    return w3.eth.contract(
        address=Web3.to_checksum_address(settings.CONTRACT_ADDRESS),
        abi=artifact["abi"],
    )


def trigger_payout(
    farmer_wallet: str,
    farm_id: str,
    payout_percent: int,
    tx_note: str,
) -> str:
    """
    Calls triggerPayout(farmId, payoutPercent, txNote) on the Sepolia contract.
    Returns the transaction hash as a hex string.
    Raises on failure — caller should catch and mark payout as failed.
    """
    w3 = _get_w3()
    if not w3.is_connected():
        raise ConnectionError("Cannot connect to Sepolia RPC")

    contract = _get_contract(w3)
    oracle = w3.eth.account.from_key(settings.ORACLE_PRIVATE_KEY)
    nonce = w3.eth.get_transaction_count(oracle.address)

    tx = contract.functions.triggerPayout(
        farm_id,
        payout_percent,
        tx_note,
    ).build_transaction({
        "from": oracle.address,
        "nonce": nonce,
        "gasPrice": w3.eth.gas_price,
        "gas": 200_000,
        "chainId": 11155111,    # Sepolia
    })

    signed = w3.eth.account.sign_transaction(tx, private_key=settings.ORACLE_PRIVATE_KEY)
    tx_hash = w3.eth.send_raw_transaction(signed.raw_transaction)
    return tx_hash.hex()


def get_pool_balance_eth() -> float:
    """Returns the contract's current ETH pool balance."""
    w3 = _get_w3()
    contract = _get_contract(w3)
    balance_wei = contract.functions.getPoolBalance().call()
    return float(w3.from_wei(balance_wei, "ether"))